-- Create the coaching_logs table for Underdogs Coaching Log
CREATE TABLE IF NOT EXISTS public.coaching_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  date text,
  coach text,
  team_name text,
  founder_name text,
  session_type text,
  session_num integer,
  stage text,
  stage_detail text,
  main_topic text,
  last_commitment text,
  last_done text,
  last_number text,
  last_result text,
  real_issue text,
  blocker_type text,
  ai_used boolean DEFAULT false,
  next_action text,
  next_deadline text,
  next_evidence text,
  next_checkin text,
  session_note text,
  watch_next text,
  energy integer,
  metrics jsonb DEFAULT '[]'::jsonb
);

-- Enable Row Level Security
ALTER TABLE public.coaching_logs ENABLE ROW LEVEL SECURITY;

-- Allow all operations for anon (public access)
CREATE POLICY "Allow all access" ON public.coaching_logs
  FOR ALL USING (true) WITH CHECK (true);
